
server:
  port: 9999

spring:
  application:
    name: bootcamp-adventureworks-apigateway

  cloud:
    gateway:
      routes:
        - id: categories-service
          uri: lb://ADVENTURE-WORKS-CATEGORIES
          predicates:
            - Path=/categories/**
        - id: products-service
          uri: lb://ADVENTURE-WORKS-PRODUCTS
          predicates:
            - Path=/products/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost


